config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

import product.views

urlpatterns = [
    path("", product.views.ProductList.as_view(), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("prokeepr.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("products/", include("product.urls")),
    path("manager/", include("manager.urls")),
    path("warehouse/", include("warehouse.urls")),
    path("manufacturer/", include("manufacturer.urls")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

product/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.ProductList.as_view(), name="all-products"),
    path('borrowed/', views.BorrowedProductList.as_view(), name="borrowed"),
    path('create/', views.ProductCreate.as_view(), name='product-create'),
    path('return/<int:pk>/', views.ProductInstanceReturn.as_view(), name="product-return"),
    path('redirect/<int:pk>/', views.ProductInstanceRedirect.as_view(), name="return-redirect"),
    path('borrow/<int:pk>/', views.ProductInstanceBorrow.as_view(), name="product-borrow"),
    path('delete/<int:pk>/', views.ProductDelete.as_view(), name='product-delete'),
    path('update/<int:pk>/', views.ProductUpdate.as_view(), name='product-update'),
]

prokeepr/users/urls.py
from django.urls import path

from prokeepr.users.views import (
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

manufacturer/models.py
from django.db import models


class Manufacturer(models.Model):
    name = models.CharField(max_length=150)

    def __str__(self):
        return self.name

product/models.py
import datetime
from django.db import models
from django.shortcuts import reverse
from django.core.exceptions import ValidationError


STATUS = (
    ('m', 'Maintenance'),
    ('o', 'On Loan'),
    ('a', 'Available')
)


def manufacturer_directory(instance, filename):
    return f'{instance.manufacturer}/{filename}'


class Product(models.Model):
    image = models.ImageField(upload_to=manufacturer_directory, null=True)
    model_number = models.CharField(max_length=255)
    serial_number = models.CharField(max_length=255, unique=True)
    human_readable_name = models.CharField(max_length=255)
    created = models.DateField(auto_now_add=True)
    bin_location = models.CharField(max_length=25)
    loan_status = models.CharField(max_length=1, choices=STATUS, default="a")

    manufacturer = models.ForeignKey('manufacturer.Manufacturer', on_delete=models.CASCADE)
    warehouse = models.ForeignKey('warehouse.Warehouse', null=True, on_delete=models.CASCADE)
    current_borrower = models.ForeignKey('users.User', blank=True, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.model_number

    def get_absolute_url(self):
        return reverse('product-detail', args=[self.pk])


def future_dates_only(date):
    if date < datetime.date.today():
        raise ValidationError("Rental End date cannot be in the past.")


class ProductInstance(models.Model):
    requested = models.DateField(auto_now_add=True)
    rental_end = models.DateField(validators=[future_dates_only])
    returned = models.DateField(blank=True, null=True)
    return_note = models.TextField(blank=True, help_text="Where you left the demo and any notes on condition")

    product = models.ForeignKey('Product', on_delete=models.CASCADE)
    borrower = models.ForeignKey('users.User', blank=True, on_delete=models.CASCADE)
    returned_to = models.ForeignKey('warehouse.Warehouse', null=True, on_delete=models.CASCADE)

    def __str__(self):
        return f"User: {self.borrower} Date: {self.requested} - {self.rental_end} " \
               f"Product: {self.product.human_readable_name}"

    def get_absolute_url(self):
        return reverse('product-instance', args=[self.pk])

prokeepr/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = CharField(_("Name of User"), blank=True, max_length=255)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

warehouse/models.py
from django.db import models

from .states import STATES


class WarehouseManager(models.Model):
    manager = models.ForeignKey('users.User', on_delete=models.CASCADE)

    def __str__(self):
        return self.manager.username


class Warehouse(models.Model):
    city = models.CharField(max_length=200)
    state = models.CharField(max_length=2, choices=STATES)
    manager = models.ForeignKey('WarehouseManager', on_delete=models.CASCADE)

    def __str__(self):
        return self.city

product/forms.py
import datetime
from django.forms import ModelForm, DateInput

from .models import ProductInstance, Product


class ReturnProductForm(ModelForm):
    class Meta:
        model = ProductInstance
        fields = ('returned_to', 'return_note')

class BorrowProductForm(ModelForm):
    class Meta:
        model = ProductInstance
        fields = ('rental_end',)
        widgets = {
            'rental_end': DateInput(attrs={
                'class': 'form-control datetimepicker-input',
                'data-target': '#id_rental_end'
            })
        }


class CreateProductForm(ModelForm):
    class Meta:
        model = Product
        exclude = ('current_borrower', 'loan_status', 'created')

prokeepr/users/forms.py
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

product/views.py
from datetime import date

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render, reverse, get_object_or_404
from django.views.generic import (
    ListView, DetailView, CreateView, UpdateView, View, RedirectView, DeleteView
)
from django.db.models import Q
from django.http import HttpResponseForbidden, HttpResponseRedirect

from .forms import ReturnProductForm, CreateProductForm, BorrowProductForm
from .models import Product, ProductInstance
from .helpers import set_product_availability, set_current_borrower


class ProductList(LoginRequiredMixin, ListView):
    model = Product
    template_name = 'product/product_list.html'
    context_object_name = 'products'
    paginate_by = 2
    ordering = ["-human_readable_name"]

    def get_queryset(self):
        queryset = super(ProductList, self).get_queryset()
        search = self.request.GET.get("q")

        if search:
            return queryset.filter(
                Q(manufacturer__name__icontains=search) |
                Q(human_readable_name__icontains=search)  |
                Q(model_number__icontains=search)
            )
        return queryset


class ProductInstanceBorrow(LoginRequiredMixin,SuccessMessageMixin, CreateView):
    model = ProductInstance
    form_class = BorrowProductForm
    template_name = 'product/product_borrow.html'
    success_message = "Demo Borrowed Successfully!"

    def dispatch(self, request, *args, **kwargs):
        self.product = get_object_or_404(Product, pk=kwargs["pk"], loan_status="a")
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        product = Product.objects.get(pk=self.kwargs['pk'])
        context['product'] = product
        return context

    def get_success_url(self):
        return reverse('all-products')

    def form_valid(self, form):
        related_product = Product.objects.get(pk=self.kwargs.get('pk'))
        set_product_availability(related_product, "o")
        set_current_borrower(related_product, self.request.user)

        form.instance.borrower = self.request.user
        form.instance.product = related_product
        return super().form_valid(form)


class ProductInstanceReturn(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = ProductInstance
    context_object_name = 'rental'
    template_name = 'product/product_return.html'
    form_class = ReturnProductForm
    success_message = "Demo Returned Successfully!"
    today = date.today()

    def get_queryset(self):
        query = super(ProductInstanceReturn, self).get_queryset()
        query = query.filter(borrower=self.request.user)
        return query

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['today'] = self.today
        return context

    def get_success_url(self):
        return reverse('all-products')

    def form_valid(self, form):
        related_product = Product.objects.get(
            pk=form.instance.product.id
        )
        set_product_availability(related_product, "a")
        set_current_borrower(related_product, None)
        form.instance.returned = self.today.strftime("%Y-%m-%d")
        return super().form_valid(form)


class BorrowedProductList(LoginRequiredMixin, ListView):
    model = Product
    template_name = 'product/product_list.html'
    context_object_name = 'products'

    def get_queryset(self):
        queryset = super(BorrowedProductList, self).get_queryset()
        borrowed_products = queryset.filter(
            current_borrower=self.request.user
        )

        search = self.request.GET.get("q")
        if search:
            return borrowed_products.filter(
                Q(manufacturer__name__icontains=search) |
                Q(human_readable_name__icontains=search)  |
                Q(model_number__icontains=search)
            )
        return borrowed_products


class ProductInstanceRedirect(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self, **kwargs):
        product = get_object_or_404(Product, pk=kwargs['pk'], loan_status="o")
        product_instance = get_object_or_404(
            ProductInstance, product=product,
            borrower=self.request.user,
            returned=None
        )
        return reverse('product-return', args=[product_instance.id])


class ProductCreate(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Product
    form_class = CreateProductForm
    template_name = 'product/product_create_update.html'
    permission_required = ('product.add_product',)
    raise_exception = True

    def get_context_data(self):
        context = super().get_context_data()
        context['form_type'] = 'create'
        return context

    def get_success_url(self):
        return reverse('all-products')


class ProductUpdate(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Product
    form_class = CreateProductForm
    template_name = 'product/product_create_update.html'
    permission_required = ('product.change_product',)
    raise_exception = True

    def get_success_url(self):
        return reverse('all-products')


class ProductDelete(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Product
    template_name = 'product/product_delete.html'
    context_object_name = 'product'
    permission_required = ('product.delete_product',)
    raise_exception = True

    def get_success_url(self):
        return reverse('all-products')

prokeepr/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView
from django.shortcuts import get_object_or_404

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"

    def get_object(self):
        return User.objects.get(username=self.request.user.username)


user_detail_view = UserDetailView.as_view()



class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

prokeepr/templates/product/product_borrow.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<!--BEGIN RENTAL FORM-->
<div class="row">
  <div class="col-md-6 col-sm-12 p-5 text-light">
    <h5>Select the date you will return the unit</h5>
    <form method="post">
      {% csrf_token %}
      <div class="form-group">
        <div class="input-group date" id="id_rental_end" data-target-input="nearest">
            {{ form.rental_end }}
          <div class="input-group-append datetimepicker-input" data-target="#id_rental_end" data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      {% if form.rental_end.errors %}
      <div>
        <p>{{ form.rental_end.errors.as_text }}</p>
      </div>
      {% endif %}
      <div class="text-center py-3">
        <button type="submit" class="button button--gold">Borrow</button>
      </div>
    </form>
  </div>



  <div class="col-md-6 col-sm-12 text-center p-md-5 p-sm-1 text-light">
    <h4 class="display-4">Your Rental Will Begin:</h4>
    <h2 class="text--gold">
      {% now 'm/d/Y' %}
    </h2>
  </div>

</div>

<!--BEGIN PRODUCT DETAILS-->
<div class="row mt-5 product__wrapper">

  <div class="col-md-4 col-sm-12 product__image-wrapper">
    {% if product.image %}
    <img class="product__image" src="{{ product.image.url }}">
    {% else %}
    <img class="product__image" src="https://via.placeholder.com/400x321">
    {% endif %}
  </div>

  <div class="col-md-4 col-sm-12 product__details">
    <h5 class="display-4 product__header">{{ product.manufacturer|title }} - {{ product.human_readable_name|title }}</h5>
    <span class="product__id">Model: {{ product.model_number }}</span>
    <span class="product__id">Serial: {{ product.serial_number }} </span>
  </div>

  <div class="col-md-4 col-sm-12 product__controls px-3">
    <h5 class="product__status">{{ product.get_loan_status_display }}</h5>
    <p>Location - {{ product.warehouse }} Warehouse</p>
  </div>

</div>

<script>
  $(function () {
    $("#id_rental_end").datetimepicker({
      format: 'L'
    });
  });
</script>

<script>
  $
</script>
{% endblock %}

prokeepr/templates/product/product_create_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row pt-md-5 pt-sm-1">
  <div class="col title">
    {% if form_type == "create" %}
    <h2 class="display-4 py-3">Create a New Product</h2>
    {% else %}
    <h2 class="display-4 py-3">Update This Product</h2>
    {% endif %}
  </div>
</div>

<div class="row justify-content-md-center text-light pb-5">
  <div class="col-md-6 col-sm-12">
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}

      <div class="form-group">
          {{ form.manufacturer|as_crispy_field }}
      </div>
      {% if perms.manufacturer.add_manufacturer %}
      <div class="form-group">
          <div class="update__related">
            <a class="update__related-icon" href="{% url 'manufacturer-create' %}?from={{ request.path|urlencode }}">
              <i class="fas fa-plus-square fa-2x "></i>
            </a>
            <span class="update__related-text">New Manufacturer</span>
          </div>
      </div>
      {% endif %}

      <div class="form-group">
          {{ form.warehouse|as_crispy_field }}
      </div>

      {% if perms.warehouse.add_warehouse %}
      <div class="form-group">
          <div class="update__related">
            <a class="update__related-icon" href="{% url 'warehouse-create' %}?from={{ request.path|urlencode }}">
              <i class="fas fa-plus-square fa-2x "></i>
            </a>
            <span class="update__related-text">New Warehouse</span>
          </div>
      </div>
      {% endif %}

      <div class="form-group">
      {{ form.bin_location|as_crispy_field }}
      {{ form.human_readable_name|as_crispy_field }}
      {{ form.model_number|as_crispy_field }}
      {{ form.serial_number|as_crispy_field }}
      {{ form.image|as_crispy_field }}
      </div>
      <div class="text-center pt-4">
        {% if form_type == "create" %}
        <button type="submit" class="button button--gold">Create</button>
        {% else %}
        <button type="submit" class="button button--gold">Update</button>
        {% endif %}
      </div>
    </form>
  </div>

</div>


{% if form.subject.errors %}
    <ol>
    {% for error in form.subject.errors %}
        <li><strong>{{ error|escape }}</strong></li>
    {% endfor %}
    </ol>
{% endif %}
{% endblock %}

prokeepr/templates/product/product_delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row pt-md-5 pt-sm-1">
  <div class="col-12 delete__header">
      <h1 class="display-3 delete__header-text">Selected Product</h1>
  </div>
</div>

<div class="row product__wrapper">
  <div class="col-md-4 col-sm-12 product__image-wrapper">
    {% if product.image %}
    <img class="product__image" src="{{ product.image.url }}">
    {% else %}
    <img class="product__image" src="https://via.placeholder.com/400x321">
    {% endif %}
  </div>

  <div class="col-md-4 col-sm-12 product__details">
    <h5 class="display-4 product__header">{{ product.manufacturer|title }} - {{ product.human_readable_name|title }}</h5>
    <span class="product__id">Model: {{ product.model_number }}</span>
    <span class="product__id">Serial: {{ product.serial_number }} </span>
  </div>

  <div class="col-md-4 col-sm-12 product__controls px-3">
    <h5 class="product__status">{{ product.get_loan_status_display }}</h5>
    <p>Location - {{ product.warehouse }} Warehouse</p>
  </div>

</div>

 <div class="row">
    <div class="col-12 delete__form-wrapper">
      <form method="post">
      {% csrf_token %}
      <div class="form-group">
        <h4 class="py-3">WARNING: ALL ASSOCIATED RENTAL HISTORY WILL ALSO BE DELETED</h4>

        <h5 class="py-3">Are you sure you want to delete this product?</h5>
        <input class="mt-3 button button--delete"  type="submit" value="Confirm">
      </div>
      </form>
    </div>
</div>
{% endblock %}

prokeepr/templates/product/product_list.html
{% extends 'snippets/infinite_scroll_window.html' %}

{% block infinite-content %}
{% include 'snippets/search_bar.html' %}

{% if products %}
{% for product in products %}
<div class="row infinite-item product__wrapper">
  <div class="col-md-4 col-sm-12 product__image-wrapper">
    {% if product.image %}
    <img class="product__image" src="{{ product.image.url }}">
    {% else %}
    <img class="product__image" src="https://via.placeholder.com/400x321">
    {% endif %}
  </div>

  <div class="col-md-5 col-sm-12 product__details">
    <h5 class="display-4 product__header">{{ product.manufacturer|title }} - {{ product.human_readable_name|title }}</h5>
    <span class="product__id">Model: {{ product.model_number }}</span>
    <span class="product__id">Serial: {{ product.serial_number }} </span>
  </div>

  <div class="col-md-3 col-sm-12 px-3 product__controls ">
    <h5 class="product__status">{{ product.get_loan_status_display }}</h5>
    <p>Location - {{ product.warehouse }} Warehouse</p>

    {% if product.current_borrower %}
    <p><b>Borrowed By:</b> {{ product.current_borrower.name }}</p>
    {% endif %}

    {% if product.loan_status == "a" %}
    <a class="button button--sea" href="{% url 'product-borrow' product.pk %}">Borrow Unit</a>

    {% elif product.loan_status == "o" and user == product.current_borrower %}
    <a class="button button--tomato" href="{% url 'return-redirect' product.pk %}">Return Unit</a>

    {% else %}
    <a class="button button--unavailable">Unavailable</a>
    {% endif %}

    {% if perms.product.update_product %}
    <div class="product__admin">
        <div><a class="button button--gold" href="{% url 'product-update' product.pk %}">Update</a></div>
      {% if perms.product.delete_product %}
        <div><a class="button button--delete" href="{% url 'product-delete' product.pk %}">Delete</a></div>
      {% endif %}
    </div>
    {% endif %}

  </div>

</div>
{% endfor %}

{% else %}
{% include 'snippets/none_borrowed.html' %}
{% endif %}
{% endblock %}

prokeepr/templates/product/product_return.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="row pt-5">
  <div class="col title">
    <h4 class="display-4 pb-4">You've had this unit since {{ rental.requested }}</h4>
    <h2 class="text--gold">That's {{ rental.requested|timesince:today }}!</h2>
  </div>
</div>

<div class="row justify-content-md-center text-light pt-5">
  <div class="col-md-6 col-sm-12">
    <form method="post">
      {% csrf_token %}
      <div class="form-group">
      <h6>Which warehouse are you returning this to?</h6>
      {{ form.returned_to|as_crispy_field }}
      <h6>Any notes on return location or condition?</h6>
      {{ form.return_note|as_crispy_field }}
      </div>
      <div class="text-center py-5">
        <button type="submit" class="button button--gold">Return</button>
      </div>
    </form>
  </div>
</div>


<!--BEGIN PRODUCT DETAILS-->
<div class="row product__wrapper">

  <div class="col-md-4 col-sm-12 product__image-wrapper">
    {% if rental.product.image %}
    <img class="product__image" src="{{ rental.product.image.url }}">
    {% else %}
    <img class="product__image" src="https://via.placeholder.com/400x321">
    {% endif %}
  </div>

  <div class="col-md-4 col-sm-12 product__details">
    <h5 class="display-4 product__header">{{ rental.product.manufacturer|title }} - {{ rental.product.human_readable_name|title }}</h5>
    <span class="product__id">Model: {{ rental.product.model_number }}</span>
    <span class="product__id">Serial: {{ rental.product.serial_number }} </span>
  </div>

  <div class="col-md-4 col-sm-12 product__controls px-3">
    <h5 class="product__status">{{ rental.product.get_loan_status_display }}</h5>
    <p>Location - {{ rental.product.warehouse }} Warehouse</p>
  </div>

</div>




{% endblock %}