config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

import product.views

urlpatterns = [
    path("", product.views.ProductList.as_view(), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("prokeepr.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("products/", include("product.urls")),
    path("manager/", include("manager.urls")),
    path("warehouse/", include("warehouse.urls")),
    path("manufacturer/", include("manufacturer.urls")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

prokeepr/users/urls.py
from django.urls import path

from prokeepr.users.views import (
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

warehouse/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.WarehouseList.as_view(), name='warehouse-list'),
    path('create-manager/', views.WarehouseManagerCreate.as_view(), name='manager-create'),
    path('create/', views.WarehouseCreate.as_view(), name='warehouse-create'),
    path('update/<int:pk>/', views.WarehouseUpdate.as_view(), name='warehouse-update'),
    path('delete/<int:pk>/', views.WarehouseDelete.as_view(), name='warehouse-delete')
]

prokeepr/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = CharField(_("Name of User"), blank=True, max_length=255)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

warehouse/models.py
from django.db import models

from .states import STATES


class WarehouseManager(models.Model):
    manager = models.ForeignKey('users.User', on_delete=models.CASCADE)

    def __str__(self):
        return self.manager.username


class Warehouse(models.Model):
    city = models.CharField(max_length=200)
    state = models.CharField(max_length=2, choices=STATES)
    manager = models.ForeignKey('WarehouseManager', on_delete=models.CASCADE)

    def __str__(self):
        return self.city

prokeepr/users/forms.py
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

prokeepr/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView
from django.shortcuts import get_object_or_404

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"

    def get_object(self):
        return User.objects.get(username=self.request.user.username)


user_detail_view = UserDetailView.as_view()



class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

warehouse/views.py
from django.shortcuts import reverse
from django.views.generic import CreateView, DeleteView, UpdateView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

from .models import Warehouse, WarehouseManager


class WarehouseCreate(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Warehouse
    fields = '__all__'
    template_name = 'warehouse/warehouse_create_update.html'
    permission_required = ('warehouse.add_warehouse',)
    raise_exception = True

    def get_context_data(self):
        context = super().get_context_data()
        context['form_type'] = 'create'
        context['from'] = self.request.GET.get('from')
        return context

    def get_success_url(self):
        next_url = self.request.GET.get('next', None)
        if next_url:
            return next_url
        else:
            return reverse('all-products')


class WarehouseUpdate(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Warehouse
    fields = '__all__'
    template_name = 'warehouse/warehouse_create_update.html'
    permission_required = ('warehouse.change_warehouse',)
    raise_exception = True


class WarehouseDelete(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Warehouse
    template_name = 'warehouse/warehouse_delete.html'
    context_object_name = 'warehouse'
    permission_required = ('warehouse.delete_product',)
    raise_exception = True


class WarehouseList(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = Warehouse
    template_name = 'warehouse/warehouse_list.html'
    context_object_name = 'warehouses'
    permission_required = ('warehouse.delete_product',)
    raise_exception = True


class WarehouseManagerCreate(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = WarehouseManager
    fields = '__all__'
    template_name = 'warehouse/warehouse_manager_create_update.html'
    permission_required = ('warehouse.add_warehouse_manager',)
    raise_exception = True

    def get_context_data(self):
        context = super().get_context_data()
        context['from'] = self.request.GET.get('from')
        return context

    def get_success_url(self):
        next_url = self.request.GET.get('next', None)
        if next_url:
            return next_url
        else:
            return reverse('all-products')

prokeepr/templates/warehouse/warehouse_create_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row pt-5">
  <div class="col title">
    {% if form_type == "create" %}
    <h2 class="display-4">Create a New Warehouse</h2>
    {% else %}
    <h2 class="display-4">Update This Warehouse</h2>
    {% endif %}
  </div>
</div>

<div class="row justify-content-md-center text-light pt-4">
  <div class="col-md-6 col-sm-12">
    <form method="post" enctype="multipart/form-data" action="{% if from %}?next={{ from }}{% endif %}">
      {% csrf_token %}
      <div class="form-group">
      {{ form.city|as_crispy_field }}
      {{ form.state|as_crispy_field }}
      {{ form.manager|as_crispy_field }}
      </div>
      <div class="text-center pt-5">
        {% if form_type == "update" %}
        <button type="submit" class="button button--gold">Update</button>
        {% else %}
        <button type="submit" class="button button--gold">Create</button>
        {% endif %}
      </div>
    </form>
  </div>
</div>


{% if form.subject.errors %}
    <ol>
    {% for error in form.subject.errors %}
        <li><strong>{{ error|escape }}</strong></li>
    {% endfor %}
    </ol>
{% endif %}
{% endblock %}

prokeepr/templates/warehouse/warehouse_delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row pt-md-5 pt-sm-1">
  <div class="col-12 delete__header">
      <h1 class="display-3 delete__header-text">Selected Warehouse</h1>
      <h2 class="display-3 delete__header-text">{{ warehouse.city }}, {{ warehouse.state }}</h2>
  </div>
</div>

 <div class="row">
    <div class="col-12 delete__form-wrapper">
      <form method="post">
      {% csrf_token %}
      <div class="form-group">
        <h4 class="py-3">WARNING: ALL ASSOCIATED RENTAL HISTORY WILL ALSO BE DELETED</h4>

        <h5 class="py-3">Are you sure you want to delete this manufacturer?</h5>
        <input class="mt-3 button button--delete"  type="submit" value="Confirm">
      </div>
      </form>
    </div>
</div>
{% endblock %}

prokeepr/templates/warehouse/warehouse_list.html
{% extends 'base.html' %}

{% block content %}
<div class="row bg--dark-blue">
  <div class="col title">
    <h1 class="display-4 p-md-5 p-sm-3">Warehouses</h1>
  </div>
</div>

<div class="row">
  <table class="table table-dark bg--dark-blue">
    <caption>List of Warehouses</caption>
    <thead>
      <tr>
          <th scope="col">City</th>
          <th scope="col">State</th>
          <th scope="col">Manager</th>
          <th scope="col"></th>
      </tr>
    </thead>
    <tbody class="infinite-container">
    {% for warehouse in warehouses %}

    <tr>
      <td scope="row">
        {{ warehouse.city }}
      </td>
      <td scope="row">
        {{ warehouse.state }}
      </td>
      <td scope="row">
        {{ warehouse.manager }}
      </td>
      <td scope="row" class="text-right">
        {% if perms.warehouse.add_warehouse %}
        <a class="button button--sea" href="{% url 'warehouse-update' warehouse.pk %}">Update</a>
        {% endif %}

        {% if perms.warehouse.delete_warehouse %}
        <a class="button button--delete" href="{% url 'warehouse-delete' warehouse.pk %}">Delete</a>
        {% endif %}

      </td>
    </tr>
    {% endfor %}
    </tbody>
  </table>
</div>

{% endblock %}

prokeepr/templates/warehouse/warehouse_manager_create_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row pt-5">
  <div class="col title">
    <h2 class="display-4">Select a Warehouse Manager</h2>
    <h5 class="text--gold">Give user warehouse manager permissions</h5>
  </div>
</div>

<div class="row justify-content-md-center text-light pt-4">
  <div class="col-md-6 col-sm-12">
    <form method="post" enctype="multipart/form-data" action="{% if from %}?next={{ from }}{% endif %}">
      {% csrf_token %}
      <div class="form-group">
      {{ form.manager|as_crispy_field }}
      </div>
      <div class="text-center pt-5">
        {% if form_type == "update" %}
        <button type="submit" class="button button--gold">Update</button>
        {% else %}
        <button type="submit" class="button button--gold">Create</button>
        {% endif %}
      </div>
    </form>
  </div>
</div>

{% if form.subject.errors %}
    <ol>
    {% for error in form.subject.errors %}
        <li><strong>{{ error|escape }}</strong></li>
    {% endfor %}
    </ol>
{% endif %}
{% endblock %}